### ISSUE TITLE
client.py monitor fails with TypeError

### ISSUE THREAD

**Issue by Marnix-vb** [Evsdd/The-Evohome-Protocol#6]
I can run:
pi@raspberrypi:~/ramses_rf $ python client.py listen /dev/ttyUSB0 -o packet.log

but if i run:
pi@raspberrypi:~/ramses_rf $ python client.py monitor /dev/ttyUSB0 -o packet.log

it fails, 

pi@raspberrypi:~/ramses_rf $ python -V
Python 3.9.2
on Raspbian GNU/Linux 11 (bullseye)

Traceback (most recent call last):
  File "/home/pi/ramses_rf/client.py", line 473, in <module>
    cli()
  File "/usr/lib/python3/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1257, in invoke
    sub_ctx = cmd.make_context(cmd_name, args, parent=ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 700, in make_context
    self.parse_args(ctx, args)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1048, in parse_args
    value, args = param.handle_parse_result(ctx, opts, args)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1623, in handle_parse_result
    value = self.full_process_value(ctx, value)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1965, in full_process_value
    return Parameter.full_process_value(self, ctx, value)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1592, in full_process_value
    value = self.get_default(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1917, in get_default
    return Parameter.get_default(self, ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1534, in get_default
    return self.type_cast_value(ctx, rv)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1561, in type_cast_value
    return self.type(value or (), self, ctx)
  File "/usr/lib/python3/dist-packages/click/types.py", line 46, in __call__
    return self.convert(value, param, ctx)
  File "/usr/lib/python3/dist-packages/click/types.py", line 681, in convert
    raise TypeError(
TypeError: It would appear that nargs is set to conflict with the composite type arity.

Thanks for looking into this!

Marnix

**Comment by Marnix-vb** [comment]
Sorry, wrong Project, will move to ramses_rf
